name: TechTrends

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: login docker
        uses: docker/login-action@v1
        with:
          username: quocanh944
          password: 1b2805fb-3fe7-4765-ba8b-a18e345f1e89

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quocanh944/techtrends:latest